### ISSUE TITLE
Timeout with Twitter stream not handled well

### ISSUE THREAD

**Issue by underscoredotspace** [underscoredotspace/teal-hawk#60]
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: read ETIMEDOUT
    at exports._errnoException (util.js:856:11)
    at TLSWrap.onread (net.js:544:26)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by underscoredotspace** [comment]
Not seen this again. Closing.
